main/urls.py
from django.urls import path
from . import views

app_name='main'

urlpatterns = [
	path('', views.IndexView.as_view(), name="home"),
	path('contact/', views.ContactView.as_view(), name="contact"),
	path('lifting/', views.LiftingView.as_view(), name="liftings"),
	path('lifting/<slug:slug>', views.LiftingDetailView.as_view(), name="lifting"),
	path('portfolio/', views.PortfolioView.as_view(), name="portfolios"),
	path('portfolio/<slug:slug>', views.PortfolioDetailView.as_view(), name="portfolio"),
    path('education/', views.EducationView.as_view(), name="educations"),
    path('education/<slug:slug>', views.EducationDetailView.as_view(), name="education"),
    path('lifting-gallery/', views.LiftingGalleryView.as_view(), name="galleries"),
    path('about-me', views.AboutMeView.as_view(), name="about-me")
]

resume/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField


class Skill(models.Model):
    class Meta:
        verbose_name_plural = 'Skills'
        verbose_name = 'Skill'
    
    name = models.CharField(max_length=20, blank=True, null=True)
    score = models.IntegerField(default=80, blank=True, null=True)
    image = models.FileField(blank=True, null=True, upload_to="skills")
    is_key_skill = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name

class UserProfile(models.Model):

    class Meta:
        verbose_name_plural = 'User Profiles'
        verbose_name = 'User Profile'
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(blank=True, null=True, upload_to="avatar")
    title = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    skills = models.ManyToManyField(Skill, blank=True)
    cv = models.FileField(blank=True, null=True, upload_to="cv")

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'


class ContactProfile(models.Model):
    
    class Meta:
        verbose_name_plural = 'Contact Profiles'
        verbose_name = 'Contact Profile'
        ordering = ["timestamp"]
    timestamp = models.DateTimeField(auto_now_add=True)
    name = models.CharField(verbose_name="Name",max_length=100)
    email = models.EmailField(verbose_name="Email")
    message = models.TextField(verbose_name="Message")

    def __str__(self):
        return f'{self.name}'



class Testimonial(models.Model):

    class Meta:
        verbose_name_plural = 'Testimonials'
        verbose_name = 'Testimonial'
        ordering = ["name"]

    thumbnail = models.ImageField(blank=True, null=True, upload_to="testimonials")
    name = models.CharField(max_length=200, blank=True, null=True)
    role = models.CharField(max_length=200, blank=True, null=True)
    quote = models.CharField(max_length=500, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Media(models.Model):

    class Meta:
        verbose_name_plural = 'Media Files'
        verbose_name = 'Media'
        ordering = ["name"]
	
    image = models.ImageField(blank=True, null=True, upload_to="media")
    url = models.URLField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    is_image = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.url:
            self.is_image = False
        super(Media, self).save(*args, **kwargs)
    def __str__(self):
        return self.name

class Lifting(models.Model):

    class Meta:
        verbose_name_plural = 'Liftings'
        verbose_name = 'Lifting'
        ordering = ["name"]
    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to="lifting")
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Lifting, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/lifting/{self.slug}"


class Portfolio(models.Model):

    class Meta:
        verbose_name_plural = 'Portfolio Profiles'
        verbose_name = 'Portfolio'
        ordering = ["timestamp"]

    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to="portfolio")
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Portfolio, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/porfolio/{self.slug}"


class Certificate(models.Model):

    class Meta:
        verbose_name_plural = 'Certificates'
        verbose_name = 'Certificate'

    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

# new class still need to add into other files, j a test

class Education(models.Model):
    class Meta:
        verbose_name_plural="Educations"
        verbose_name="Education"
        
    year = models.DateField(blank=True, null=True)
    name = models.CharField(max_length=150, blank=True, null=True)
    skills = models.ManyToManyField(Skill, null=True)
    slug=models.SlugField(null=True, blank=True)
    body = RichTextField(blank=True, null=True)
    is_active=models.BooleanField(default=True) 

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Education, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/education/{self.slug}"
    
class LiftingGallery(models.Model):
    class Meta:
        verbose_name_plural="Galleries"
        verbose_name="Gallery"
    name = models.CharField(blank=True, null=True, max_length=50)
    file = models.FileField(blank=True, null=True, upload_to="gallery_files")
    is_active= models.BooleanField(default=True)

    def __str__(self):
        return self.name

class AboutMe(models.Model):
    class Meta:
        verbose_name_plural="About Profiles"
        verbose_name="About Me"
    name=models.CharField(blank=True, null=True, max_length=150)
    image=models.ImageField(blank=True, null=True, upload_to="me")
    body=RichTextField(blank=True, null=True)
    is_active=models.BooleanField(default=True)

    def __str__(self):
        return self.name

main/forms.py
from django import forms
from .models import ContactProfile

class ContactForm(forms.ModelForm):
    name=forms.CharField(max_length=100, required=True,
                         widget=forms.TextInput(attrs={
                             'placeholder':'*Full nmae...'
                         }))
    email=forms.EmailField(max_length=254, required=True,
                           widget=forms.TextInput(attrs={
                               'placeholder':'*Email...',  
                           }))
    message=forms.CharField(max_length=1000, required=True,
                            widget=forms.Textarea(attrs={
                                'placeholder': '*Message...',
                                'rows':10,
                            }))
    
    class Meta:
        model=ContactProfile
        fields=('name', 'email', 'message',)

main/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.contrib import messages
from .models import (
    UserProfile,
    Portfolio,
    Lifting,
    Testimonial,
    Certificate,
    Education,
    LiftingGallery,
    AboutMe
)
from django.views import generic
from . forms import ContactForm

class IndexView(generic.TemplateView):
    template_name="main/index.html"
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)

        testimonials = Testimonial.objects.filter(is_active=True)
        certificates = Certificate.objects.filter(is_active=True)
        portfolios = Portfolio.objects.filter(is_active=True)
        lifting = Lifting.objects.filter(is_active=True)
        context["testimonials"] = testimonials
        context["certificates"] = certificates
        context["projects"] = portfolios
        context["lifting"] = lifting
        return context

class ContactView(generic.FormView):
     template_name="main/contact.html"
     form_class=ContactForm
     success_url="/"
     def form_valid(self, form):
          form.save()
          messages.sucess(self.request, 'Thank you. We will be in touch soon.')
          return super().form_vaild(form)
    
class LiftingView(generic.ListView):
     model=Lifting
     template_name="main/lifting.html"
     paginate_by=10

     def get_queryset(self) -> QuerySet[Any]:
          return super().get_queryset().filter(is_active=True)
class LiftingDetailView(generic.DetailView):
     model=Lifting
     template_name="main/lifting-detail.html"

class PortfolioView(generic.ListView):
     model=Portfolio
     template_name="main/portfolio.html"
     paginate_by=10

     def get_queryset(self) -> QuerySet[Any]:
          return super().get_queryset().filter(is_active=True)
class PortfolioDetailView(generic.DetailView):
     model=Portfolio
     template_name="main/portfolio-detail.html"

class EducationView(generic.ListView):
     model=Education
     template_name="main/education.html"
     paginate_by=10
     
     def get_queryset(self) -> QuerySet[Any]:
          return super().get_queryset().filter(is_active=True)
     
class EducationDetailView(generic.DetailView):
     model=Education
     template_name="main/education-detail.html"

class LiftingGalleryView(generic.ListView):
     model=LiftingGallery
     template_name="main/lifting-gallery.html"

class AboutMeView(generic.TemplateView):
     model=AboutMe
     template_name="main/about-me.html"

main/templates/main/about-me.html
{% extends 'main/base.html' %}
{% load static %}

<!--start seo blocks-->
{% block title %}{% endblock %}
{% block description %}{% endblock %}
{% block keywords %}{% endblock %}
<!--end seo blocks-->

<!--start css blocks-->
{% block extend_header %}{% endblock %}
<!--end css blocks-->

<!--start script blocks-->
{% block extend_footer %}{% endblock %}
<!--end script blocks-->

<!-- start content blocks-->
{% block content %}
<section>
    <div class="innerPageBannerCol">
        <div class="container">
            <div class="row g-4g-md-3 align-items-center">
                <div class="col-md-6">
                    <div class="bannerContent">
                        <h1 class="xlTitle pb-md-3">About Me!</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>    
</section>
<section>
    <div class="sectionSpace">
        <div class="container">
            {{object.body}}
        </div>
    </div>
</section>
{% endblock %}
  

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="eng">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content='width=device-width, initial-scale=1'>

        <title>{% block title %}{% endblock %}</title>
        <meta name="author" content="Akshat Guduru">
        <link rel="canonical" href="{{request.path}}"/>
        <link rel="home"  herf="{% url 'main:home' %}"/>
        <meta name="description" content="{% block description %}{%endblock %}"/>
        <meta name="keywords" content="{% block keywords %}{%endblock %}"/>

        <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/icon.jpg' %}"/>
        <link rel="apple-touch-icon" type="images/jpg" href="{% static 'images/icon.jpg' %}"/>
        <!--============
            Start CSS
        =============-->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://unpkg.com/swiper@7.0.5/swiper-bundle.css">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        {%block extend_header%}{%endblock%}

        </head>
        <body>
            {% include 'main/partials/messages.html' %}
            {% include 'main/partials/nav.html' %}

            {% block content %}
            {% endblock %}

            {% include 'main/partials/footer.html' %}


            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
            <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
            <script src="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.js"></script>
            <script src="{% static 'js/script.js' %}"></script>
            {% block extend_footer %}{%endblock%}
        </body>
</html>

main/templates/main/education-detail.html
{% extends 'main/base.html' %}
{% load static %}

<!--start seo blocks-->
{% block title %}{% endblock %}
{% block description %}{% endblock %}
{% block keywords %}{% endblock %}
<!--end seo blocks-->

<!--start css blocks-->
{% block extend_header %}{% endblock %}
<!--end css blocks-->

<!--start script blocks-->
{% block extend_footer %}{% endblock %}
<!--end script blocks-->

<!-- start content blocks-->
{% block content %}
<section>
    <div class="innerPageBannerCol">
        <div class="row g-4 g-md-3 align-items-center">
            <div class="col-md-6">
                <div class="bannerContent">
                    <h1 class="xlTitle pb-md-3">{{object.name}}|title</h1>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-auto">
                <div class="authorCol">
                    <h4 class="smTitle pb-3">Graduation: {{object.year}}</h4>
                </div>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="sectionSpace">
        <div class="container">
            {{object.skills}}
            {{object.body|safe}}
        </div>
    </div>
</section>
{% endblock %}

main/templates/main/education.html
{% extends 'main/base.html' %}
{% load static %}

<!--start seo blocks-->
{% block title %}{% endblock %}
{% block description %}{% endblock %}
{% block keywords %}{% endblock %}
<!--end seo blocks-->

<!--start css blocks-->
{% block extend_header %}{% endblock %}
<!--end css blocks-->

<!--start script blocks-->
{% block extend_footer %}{% endblock %}
<!--end script blocks-->

<!-- start content blocks-->
{% block content %}
<section>
    <div class="innerPageBannerCol">
        <div class="container">
            <div class="row g-4 g-md-3 align-items-center">
                <div class="col-md-6">
                    <div class="bannerContent">
                        <h1 class="xlTitle pb-md-3">See My Schools!</h1>
                </div>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="lightBg">
        <div class="container">
            <div class="portfolioContentMain">
                <div class="row g-3 g-md-4 g-lg-5 educationRow">
                    {% for object in object_list %}
                    <div class="col-md-6 pColMain">
                        <div class="pCol">
                            <a href="{% url 'main:education' slug=object.slug %}">
                                {{object.name}}
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

<!--start SEO blocks-->
{% block title %}{% endblock %}
{% block description %}{% endblock %} 
{% block keywords %}{% endblock %}
<!-- end SEP blocks-->
<!--start css blocks-->
{% block extender_header %}{% endblock %}
<!--end css blocks-->

<!--start script blocks-->
{% block extender_footer %}{% endblock %}
<!--end srtipt blocks-->

<!--start content-->
{% block content %}
    <section>
        <div class="bannerSection">
            <div class="container">
                <div class="row g-4 g-md-3  align-items-center">
                    <div class="col-md-auto order-md-last">
                        <div class="bannerUserImg">
                            <img src="{{me.userprofile.avatar.url}}" alt="{{me.first_name|title}} {{me.last_name|title}} avatar">
                        </div>
                    </div>
                <div class="col-md">
                    <div class="bannerContent">
                        <h1 class="xlTitle pb-3">Hi, I'm <br> {{me.userprofile.title}}. </br></h1>
                        <p>{{me.userprofile.bio}}</p>
                        <div class="bannerBtnCol">
                            <div class="row">
                                <div class="col-auto">
                                    <a download href="{{me.userprofile.cv.url}}" class="btn btnPrimary">Download Resume</a>
                                
                            </div>
                             <div class="col-auto">
                                <a href="{% url 'main:contact' %}" class="btn btnOutline">Contact</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    <section>
        <div class="sectionSpace pt-0">
        <div class="container">
            <div class="row">
            <div class="col-md-auto">
                <div class="keySkillCol">
                <h4 class="smTitle pb-3">Key Skills</h4>
                {% for sk in me.userprofile.skills.all %}
                {% if sk.is_key_skill %}
                <div class="keySkillCard">
                    {% if sk.image %}
                    <div class="ksIconCol">
                    <img src="{{sk.image.url}}" alt="...">
                    </div>
                    {% endif %}
                    <span class="ksText">{{sk.name}}</span>
                </div>
                {% endif %}
                {% endfor %}
                </div>
            </div>
            <div class="col-md">
                <h4 class="smTitle pb-3">Coding Skills</h4>
                <div class="progressCol">
                <div class="progressCard">
                    {% for sk in me.userprofile.skills.all %}
                    {% if sk.is_key_skill %}
                    <div class="progressCol">
                    <span class="progressLbl">{{sk.name}}</span>
                    <div class="row g-2 align-items-center">
                        <div class="col">
                        <div class="progress progressStyle">
                            <div class="progress-bar" role="progressbar" style="width: {{sk.score}}%" aria-valuenow="{{sk.score}}" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        </div>
                        <div class="col-auto">
                        <span class="pLbl">{{sk.score}}%</span>
                        </div>
                    </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                    
                </div>
                </div>
            </div>
            </div>
        </div>
        </div>
    </section>
    
    <section>
        <div class="sectionSpaceSm lightBg">
            <div class="container">
                <div class="row pb-3">
                    <div class="col">
                        <h4 class="smTitle regular">Certifitcates</h4>
                    </div>
                </div>
                <div class="sliderOuter">
                    <div class="swiper certificatesSlider">
                        <div class="swiper-wrapper">
                            {% for cert in certificates %}
                            {% if cert.is_active %}
                            <div class="swiper-slide">
                                <div class="cardStyle1">
                                    <h4 class="mdTitle cs1Title">
                                        <a href="javascript:void(0)">{{cert.title}}</a>
                                    </h4>
                                    <ul class="cardOptionCol">
                                        <li>{{cert.date}}</li>
                                        <li>{{cert.name|title}}</li>
                                    </ul>
                                    <p>{{cert.description}}</p>
                                </div>
                            </div>
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="cert-swiper-button-next swiper-button-next swiperBtnStyle"></div>
                    <div class="cert-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
                    <div class="swiper-pagination swiperPaginationStyle posInitial"></div>
                </div>
            </div>
        </div>
    </section>

    <section>
        <div class="lightBg">
            <div clas="container">
                <div class="BlogCol">
                    <div class="row-pb-3">
                        <div class="col">
                            <div class="portfolioCol">
                                <h4 class="smTitle pb-3 d-block">Check Out My Recent <a href="{% url 'main:portfolios' %}" class="hover-bold">Projects!</a></h4>
                            </div>
                        </div>
                    </div>
                    {% for proj in portflio %}
                    {% if proj.is_active %}
                    <div class="portfolioCard">
                        <div class="row g-4 align-items-center">
                            <div class="col-md-auto">
                                <div class="portfolioImgCol">
                                    <a href="{% url 'main:portfolio' slug=proj.slug %}"><img scr="{{proj.image.url}}" alt="..."></a>
                                </div>
                            </div>
                            <div class="col-md">
                                <div class="portfolioContentCol">
                                    <h4 class="lgTitle"><a href="{% url 'main:portfolio' slug=proj.slug %}">{{proj.name}}</a></h4>
                                    <ul class="portfolioOption">
                                        <li><span class="dateLBl">{{proj.date.year}}</span></li>
                                    </ul>
                                    <p>{{p.desription}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="sectionSpace">
            <div class="container">
                <div class="testimonaialCol">
                    <div class="row pb-3">
                        <div class="col">
                            <div class="testimonialCol">
                                <h4 class="smTitle pb-3 d-block">Tesimonials</h4>
                                <div class="testimonialSlider">
                                    <div class="swiper testimonialSwiper">
                                        <div class="swiper-wrapper">
                                            {% for test in testimonials %}
                                            {% if test.is_active %}
                                            <div class="swiper-slide">
                                                <div class="testimonialCard">
                                                    <div class="row align-items-center">
                                                        <div class="col-sm-auto">
                                                            <div class="testImgCol">
                                                                <img src="{{test.thumbnail.url}}" alt="...">
                                                            </div>
                                                        </div>
                                                        <div class="col-sm">
                                                            <div class="testContentCol">
                                                                <h4 class="xsTitle bold">{{test.name}} - {{test.role}}</h4>
                                                                <p>{{test.quote}}</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            {% endif %}
                                            {% endfor %}
                                        </div>
                                        <div class="test-swiper-button-next swiper-button-next swiperBtnStyle"></div>
                                        <div class="test-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="sectionSpaceSm lightBg">
            <div class="container">
                <div class="row pb-3">
                    <div class="col">
                        <h4 class="smTitle pb-3">Check Out My Lifting Page</h4>
                    </div>
                    <div class="col-auto">
                        <a href="{% url 'main:liftings' %}" class="hover-bold">Click here!</a>
                    </div>
                </div>
                <div class="row g-3">
                    {% for lifting in liftings %}
                    {% if lifting.is_active %}
                    <div class="col-lg-6">
                        <div class="cardStyle1">
                            <h4 class="mdTitle cs1Title"><a href ="{% url 'main:lifting' slug=lifting.slug %}">{{lifting.name}}</a></h4>
                            <ul class="cardOptionCol">
                                <li>{{lifting.timestamp.date}}</li>
                                <li>{{lifting.author}}</li>
                            </ul>
                            <p>{{lifting.description}}</p>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

main/templates/main/lifting.html
{% extends 'main/base.html' %}
{% load static %}

<!--start seo blocks-->
{% block title %}{% endblock %}
{% block description %}{% endblock %}
{% block keywords %}{% endblock %}
<!--end seo blocks-->

<!--start css blocks-->
{% block extend_header %}{% endblock %}
<!--end css blocks-->

<!--start script blocks-->
{% block extend_footer %}{% endblock %}
<!--end script blocks-->

<!-- start content blocks-->
{% block content %}
    <section>
        <div class="innerPageBanner">
            <div class="container">
                <div class="row g-4 g-md-3  align-items-center">
                    <div class="col-md-6">
                        <div class="bannerContent">
                            <h1 class="xlTitle pb-md-3">Welcome to my lifting page</h1>
                            <h2 class="smTitle pb-md-3">Visit My <a href="{% url 'main:galleries' %}" class="simpleLink">Gallery!</a></h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </section>
        
        <section>
        <div class="lightBg">
            <div class="container">
                <div class="portfolio">
                    <div class="row g-3 g-md-4 g-lg-5 liftingRow">
                        {% for object in object_list %}
                        <div class="col-md-6 pColMain">
                            <div class="pCol">
                                <a href="{% url 'main:lifting' slug=object.slug %}">
                                {{object.name}}
                                </a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

main/templates/main/portfolio.html
{% extends 'main/base.html' %}
{% load static %}

<!--start seo blocks-->
{% block title %}{% endblock %}
{% block description %}{% endblock %}
{% block keywords %}{% endblock %}
<!--end seo blocks-->

<!--start css blocks-->
{% block extend_header %}{% endblock %}
<!--end css blocks-->

<!--start script blocks-->
{% block extend_footer %}{% endblock %}
<!--end script blocks-->

<!-- start content blocks-->
{% block content %}
    <section>
        <div class="innerPageBanner">
            <div class="container">
                <div class="row g-4 g-md-3  align-items-center">
                    <div class="col-md-6">
                        <div class="bannerContent">
                            <h1 class="xlTitle pb-md-3">See my recent projects below</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="lightBg">
            <div class="container">
                <div class="portfolioContentMain">
                    <div class="row g-3 g-md-4 g-lg-5 portfolioRow">
                        {% for object in object_list %}
                        <div class="col-md-6 pColMain">
                            <div class="pCol">
                                <a href="{% url 'main:portfolio' slug=object.slug %}"><img src="{{object.image.url}}" alt="..." class="pImg"></a>
                                <h4 class="smTitle">{{object.name}}</h4>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
<!--end content-->